task_service/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tasks
  get '/sessions/sign_in' => 'sessions#new'
  post '/sessions/sign_in' => 'sessions#create'
  delete '/sessions/sign_out' => 'sessions#destroy'
  resources :registrations, only: %i[new create], path: 'sign_up'

  get 'up' => 'rails/health#show', as: :rails_health_check
end

task_service/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

task_service/app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  validates :title, :message, presence: true

  belongs_to :task, optional: false
  belongs_to :user, optional: false
end

task_service/app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  validates_url_format_of :url

  enum status: { pending: 0, in_progress: 1, completed: 2, failed: 3 }, _default: 0

  belongs_to :user, optional: false

  has_one :task_content, dependent: :delete
  has_many :notifications, dependent: :delete_all
end

task_service/app/models/task_content.rb
# frozen_string_literal: true

class TaskContent < ApplicationRecord
  validates :content, presence: true

  belongs_to :task, optional: false
end

task_service/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :tasks, dependent: :delete_all
  has_many :notifications, dependent: :delete_all
end

task_service/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def authenticate_request!
    token = cookies[:jwt_token] || params[:jwt_token] || request.headers['Authorization']&.split&.last
    if token.present?
      begin
        decoded_token = decode_jwt(token)
        @current_user = User.find(decoded_token['sub'])
      rescue JWT::DecodeError, ActiveRecord::RecordNotFound
        redirect_to sessions_sign_in_url
      end
    else
      redirect_to sessions_sign_in_url
    end
  end

  def setup_jwt_cookie(token)
    cookies[:jwt_token] = {
      value: token,
      expires: 1.day.from_now,
      secure: Rails.env.production?,
      httponly: true
    }
  end

  def decode_jwt(token)
    secret_key = ENV.fetch('DEVISE_JWT_SECRET_KEY', nil)
    JWT.decode(token, secret_key, Rails.env.production?, algorithm: 'HS256').first
  end
end

task_service/app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    response, token = AuthService.sign_up(email: sign_up_params[:email], password: sign_up_params[:password],
                                          name: sign_up_params[:name])
    if response.code == 204
      @current_user = response.body
      setup_jwt_cookie(token)
      redirect_to tasks_url
    else
      flash[:errors] = response.body
      redirect_to registrations_url
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password)
  end
end

task_service/app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    response, token = AuthService.sign_in(password: sign_in_params[:password], email: sign_in_params[:email])
    if response.code == 204
      @current_user = response.body
      setup_jwt_cookie(token)
      redirect_to tasks_url
    else
      flash[:errors] = response.body
      redirect_to sessions_sign_in_path
    end
  end

  def destroy
    AuthService.sign_out
    cookies.delete(:jwt_token)
    redirect_to sessions_sign_in_path
  end

  protected

  def sign_in_params
    params.require(:user).permit(:email, :password)
  end
end

task_service/app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :authenticate_request!
  before_action :load_notifications
  before_action :find_task, only: %i[destroy update edit show]
  include TaskHelper

  def index
    @tasks = @current_user.tasks
  end

  def show; end

  def new
    @task = Task.new
  end

  def edit; end

  def create
    @task = @current_user.tasks.new(task_params)
    if @task.save
      NotificationService.notify(@task)
      ScrapingService.notify(@task)
      redirect_to tasks_url, notice: 'Task was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @task.update(task_params)
      NotificationService.notify(@task)
      ScrapingService.notify(@task)
      redirect_to tasks_url, notice: 'Task was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private

  def load_notifications
    @notifications = @current_user.notifications
  end

  def find_task
    @task = @current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:url)
  end
end

task_service/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

task_service/app/helpers/task_helper.rb
# frozen_string_literal: true

module TaskHelper
  def badge(task)
    badges = {
      'in_progress' => 'badge text-bg-primary',
      'completed' => 'badge text-bg-success',
      'failed' => 'badge text-bg-danger',
      'pending' => 'badge text-bg-secondary'
    }
    badges[task.status]
  end
end

task_service/app/views/layouts/_navbar.html.erb
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Tasks', tasks_url, class: 'navbar-brand' %>
    <div class="d-flex">

      <div class="dropdown">
        <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa-regular fa-bell"></i>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <% @notifications.each do |notification| %>
            <li>
             <strong><%= notification.title %></strong><br>
              <small><%= notification.message %></small>
            </li>
          <% end %>
        </ul>
      </div>

      <%= link_to "Sign Out", sessions_sign_out_path(action: :delete),
                  class: 'btn btn-link',
                  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
    </div>
  </div>
</nav>

task_service/app/views/layouts/_welcome.html.erb
<div class="container">
  <div class="alert alert-primary" role="alert">
    Hi <%= @current_user.name %>
  </div>
</div>

task_service/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskService</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/e102c7ec34.js" crossorigin="anonymous"></script>
</head>

<body>
<% if @current_user.present? %>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/welcome' %>
<% end %>
<%= yield %>
</body>
</html>

task_service/app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= hidden_field_tag :jwt_token, cookies[:jwt_token] %>

  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit 'Add', class: 'btn btn-primary' %>
  </div>
<% end %>

task_service/app/views/tasks/_task.html.erb
<tr>
  <td><%= task.id %></td>
  <td style="width: 70%"><%= link_to task.url, task_path(task), class: 'btn btn-link' %></td>
  <td><%= tag.span task.status, class: badge(task) %></td>
  <td>
    <%= link_to edit_task_path(task), class: 'btn btn-link' do %>
      <i class="fa-regular fa-pen-to-square"></i>
    <% end %>
    <%= link_to task_path(action: :delete, id: task.id),
                class: 'btn btn-danger',
                data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
      <i class="fa-regular fa-trash-can"></i>
    <% end %>
  </td>
</tr>

task_service/app/views/tasks/edit.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      Editing task
    </div>
    <div class="card-body">
      <%= render "form", task: @task %>

      <br>

      <div>
        <%= link_to "Show this task", @task %> |
        <%= link_to "Back to tasks", tasks_path %>
      </div>
    </div>
  </div>
</div>

task_service/app/views/tasks/index.html.erb
<div class="container">
  <div style="display: flex; justify-content: space-between">
    <h3>My Tasks</h3>
    <%= link_to new_task_path, class: 'btn btn-primary' do %>
      <i class="fa-solid fa-plus"></i>
    <% end %>
  </div>

  <table class="table table-striped center" style="text-align: center">
    <thead>
    <tr >
      <th>ID</th>
      <th>URL</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <%= render @tasks %>
    </tbody>
  </table>
</div>

task_service/app/views/tasks/new.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      New Task
    </div>
    <div class="card-body">
      <%= render "form", task: @task %>

      <br>

      <div>
        <%= link_to "Back to tasks", tasks_path %>
      </div>
    </div>
  </div>
</div>

task_service/app/views/tasks/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      Task: #<%= @task.id %> <%= tag.span @task.status, class: badge(@task) %>
    </div>
    <div class="card-body">
      <div>
        <h3></h3>
        <p>
          URL: <%= @task.url %>
        </p>
      </div>
      <span class="badge badge-warning">Warning</span>
      <div>
        <%= @task.task_content&.content %>
      </div>
    </div>
  </div>
</div>